name: Build and Release C# Application

on:
  push:
    tags:
      - 'v*'  # Triggers only when a new version tag (e.g., v1.0.0) is pushed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust based on your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish as .exe
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish

      - name: Get Version from .csproj
        id: get_version
        run: |
          $version = (Get-Content **/*.csproj | Select-String '<Version>(.*?)</Version>' | ForEach-Object { $_.Matches.Groups[1].Value })[0]
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: pwsh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🚀 New Release: ${{ github.ref_name }}
            - Auto-packaged .exe file
            - Version: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: publish/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
